//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEeToDoList.WebApi.Models.Data
{
    /// <summary>
    /// This part of the class contains the derivation for the 'TdList'.
    /// </summary>
    partial class TdList : ModelObject
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static TdList Create()
        {
            BeforeCreate();
            var result = new TdList();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(SEeToDoList.WebApi.Models.Data.TdList model);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public static SEeToDoList.WebApi.Models.Data.TdList Create(SEeToDoList.Logic.Entities.Data.TdList entity)
        {
            var handled = false;
            var result = default(SEeToDoList.WebApi.Models.Data.TdList);
            BeforeCreate(entity, ref result, ref handled);
            if (handled == false || result is null)
            {
                var visitedEntities = new List<object> { entity };
                result = new SEeToDoList.WebApi.Models.Data.TdList();
                (result as SEeToDoList.Common.Contracts.Data.ITdList).CopyProperties(entity);
                if (entity.Tasks is not null)
                {
                    foreach (var item in entity.Tasks)
                    {
                        var listItem = SEeToDoList.WebApi.Models.Data.TdTask.Create(visitedEntities, item);
                        if (listItem is not null)
                        {
                            result.Tasks.Add(listItem);
                        }
                    }
                }
            }
            AfterCreate(entity, result);
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        internal static SEeToDoList.WebApi.Models.Data.TdList? Create(List<object> visitedEntities, SEeToDoList.Logic.Entities.Data.TdList entity)
        {
            var result = default(SEeToDoList.WebApi.Models.Data.TdList);
            if (visitedEntities.Contains(entity) == false)
            {
                visitedEntities.Add(entity);
                result = new SEeToDoList.WebApi.Models.Data.TdList();
                (result as SEeToDoList.Common.Contracts.Data.ITdList).CopyProperties(entity);
                if (entity.Tasks is not null)
                {
                    foreach (var item in entity.Tasks)
                    {
                        var listItem = SEeToDoList.WebApi.Models.Data.TdTask.Create(visitedEntities, item);
                        if (listItem is not null)
                        {
                            result.Tasks.Add(listItem);
                        }
                    }
                }
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate(SEeToDoList.Logic.Entities.Data.TdList entity, ref SEeToDoList.WebApi.Models.Data.TdList? model, ref bool handled);
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(SEeToDoList.Logic.Entities.Data.TdList entity, SEeToDoList.WebApi.Models.Data.TdList model);
    }
}
