//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEeToDoList.WebApi.Models.Data
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class TdTaskEdit
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static TdTaskEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="TdTaskEdit"/> class (created by the generator.)
        /// </summary>
        public TdTaskEdit()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        public System.String? Description { get; set; }
        /// <summary>
        /// Property 'DueDate' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'DueDate' generated by the generator.
        /// </summary>
        public System.DateTime? DueDate { get; set; }
        /// <summary>
        /// Property 'CompletedOn' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'CompletedOn' generated by the generator.
        /// </summary>
        public System.DateTime? CompletedOn { get; set; }
        /// <summary>
        /// Property 'IsCompleted' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'IsCompleted' generated by the generator.
        /// </summary>
        public System.Boolean IsCompleted { get; set; }
        /// <summary>
        /// Property 'Priority' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Priority' generated by the generator.
        /// </summary>
        public System.Int32 Priority { get; set; }
        /// <summary>
        /// Property 'TdListId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'TdListId' generated by the generator.
        /// </summary>
        public IdType TdListId { get; set; }
        /// <summary>
        /// Property 'TdList' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'TdList' generated by the generator.
        /// </summary>
        public SEeToDoList.WebApi.Models.Data.TdList? TdList { get; set; }
    }
}
