//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEeToDoList.WebApi.Models.Data
{
    using System;
    /// <summary>
    /// This model represents a transmission model for the 'TdTask' data unit.
    /// </summary>

    public partial class TdTask : SEeToDoList.Common.Contracts.Data.ITdTask
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static TdTask()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="TdTask"/> class (created by the generator.)
        /// </summary>
        public TdTask()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        public System.String? Description { get; set; }
        /// <summary>
        /// Property 'DueDate' generated by the generator.
        /// </summary>
        public System.DateTime? DueDate { get; set; }
        /// <summary>
        /// Property 'CompletedOn' generated by the generator.
        /// </summary>
        public System.DateTime? CompletedOn { get; set; }
        /// <summary>
        /// Property 'IsCompleted' generated by the generator.
        /// </summary>
        public System.Boolean IsCompleted { get; set; }
        /// <summary>
        /// Property 'Priority' generated by the generator.
        /// </summary>
        public System.Int32 Priority { get; set; }
        /// <summary>
        /// Property 'TdListId' generated by the generator.
        /// </summary>
        public IdType TdListId { get; set; }
        /// <summary>
        /// Property 'TdList' generated by the generator.
        /// </summary>
        public SEeToDoList.WebApi.Models.Data.TdList? TdList { get; set; }
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="obj">The object to compare with the current object.</param>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Data.TdTask other)
            {
                result = base.Equals(other) && IsEqualsWith(Title, other.Title)
                    && IsEqualsWith(Description, other.Description)
                    && DueDate == other.DueDate
                    && CompletedOn == other.CompletedOn
                    && IsCompleted == other.IsCompleted
                    && Priority == other.Priority
                    && TdListId == other.TdListId;
            }
            return result;
        }
        /// <summary>
        /// Serves as the default hash function.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(base.GetHashCode(), Title, Description, DueDate, CompletedOn, IsCompleted, Priority, TdListId);
        }
    }
}
