//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEeToDoList.WebApi.Models.Data
{
    /// <summary>
    /// This part of the class contains the derivation for the 'TdTask'.
    /// </summary>
    partial class TdTask : ModelObject
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static TdTask Create()
        {
            BeforeCreate();
            var result = new TdTask();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(SEeToDoList.WebApi.Models.Data.TdTask model);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public static SEeToDoList.WebApi.Models.Data.TdTask Create(SEeToDoList.Logic.Entities.Data.TdTask entity)
        {
            var handled = false;
            var result = default(SEeToDoList.WebApi.Models.Data.TdTask);
            BeforeCreate(entity, ref result, ref handled);
            if (handled == false || result is null)
            {
                var visitedEntities = new List<object> { entity };
                result = new SEeToDoList.WebApi.Models.Data.TdTask();
                (result as SEeToDoList.Common.Contracts.Data.ITdTask).CopyProperties(entity);
                if (entity.TdList is not null)
                {
                    result.TdList = SEeToDoList.WebApi.Models.Data.TdList.Create(visitedEntities, entity.TdList);
                }
            }
            AfterCreate(entity, result);
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        internal static SEeToDoList.WebApi.Models.Data.TdTask? Create(List<object> visitedEntities, SEeToDoList.Logic.Entities.Data.TdTask entity)
        {
            var result = default(SEeToDoList.WebApi.Models.Data.TdTask);
            if (visitedEntities.Contains(entity) == false)
            {
                visitedEntities.Add(entity);
                result = new SEeToDoList.WebApi.Models.Data.TdTask();
                (result as SEeToDoList.Common.Contracts.Data.ITdTask).CopyProperties(entity);
                if (entity.TdList is not null)
                {
                    result.TdList = SEeToDoList.WebApi.Models.Data.TdList.Create(visitedEntities, entity.TdList);
                }
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate(SEeToDoList.Logic.Entities.Data.TdTask entity, ref SEeToDoList.WebApi.Models.Data.TdTask? model, ref bool handled);
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(SEeToDoList.Logic.Entities.Data.TdTask entity, SEeToDoList.WebApi.Models.Data.TdTask model);
    }
}
