//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEeToDoList.MVVMApp.ViewModels.Data
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class TdTaskViewModel : GenericItemViewModel<Models.Data.TdTask>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static TdTaskViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="TdTaskViewModel"/> class (created by the generator.)
        /// </summary>
        public TdTaskViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title
        {
            get
            {
                return Model.Title;
            }
            set
            {
                Model.Title = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        public System.String? Description
        {
            get
            {
                return Model.Description;
            }
            set
            {
                Model.Description = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'DueDate' generated by the generator.
        /// </summary>
        public System.DateTime? DueDate
        {
            get
            {
                return Model.DueDate;
            }
            set
            {
                Model.DueDate = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'CompletedOn' generated by the generator.
        /// </summary>
        public System.DateTime? CompletedOn
        {
            get
            {
                return Model.CompletedOn;
            }
            set
            {
                Model.CompletedOn = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'IsCompleted' generated by the generator.
        /// </summary>
        public System.Boolean IsCompleted
        {
            get
            {
                return Model.IsCompleted;
            }
            set
            {
                Model.IsCompleted = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Priority' generated by the generator.
        /// </summary>
        public System.Int32 Priority
        {
            get
            {
                return Model.Priority;
            }
            set
            {
                Model.Priority = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'TdListId' generated by the generator.
        /// </summary>
        public IdType TdListId
        {
            get
            {
                return Model.TdListId;
            }
            set
            {
                Model.TdListId = value;
                OnPropertyChanged();
            }
        }
    }
}
